### PR TITLE
Added Uptime Logs (Percentage of bot's uptime like 99% online) (Not Added In Webpage/Bot Page) + Added Vote Webhooks (dcwebhhook means discord integration webhook and webhook means post method like top.gg)

### PR DESCRIPTION
**Pull request by dhvitish**
It is in quick.db btw because i am not much good at mongo

### CODE REVIEW

**Comment by clqu** [comment]
Can you provide proof that it works?

**Comment by dhvitish** [comment]
https://bots.solonodes.xyz this is my fork

**Comment by dhvitish** [comment]
https://discord.gg/7tJgkKvZGE Discord Server you can check it's uptime logs channel

**Comment by dhvitish** [comment]
Also there is command of uptime in the main bot

**Comment by dhvitish** [comment]
IMG_20210914_102117

**Comment by dhvitish** [comment]
IMG_20210914_102237

**Comment by dhvitish** [comment]
IMG_20210914_102349

**Comment by dhvitish** [comment]
Just change web page I didn't edited the webpage

**Comment by dhvitish** [comment]
I just did the saving of database

**Comment by dhvitish** [comment]
I pulled this request because many forks of vCodes were asking me for this code

Btw I am vCodes support server helper XD

**Comment by dhvitish** [comment]
You can also check disbots.xyz support server uptime logs channel

**Comment by dhvitish** [comment]
@clqu

**Comment by dhvitish** [comment]
Added Vote Webhooks (dcwebhhook means discord integration webhook and webhook means post method like top.gg)

**Pull request merged**
